import Footerprimary from '@/components/footerPrimary';
import TranslationsProvider from '@/components/translations-provider';
import { Toaster } from '@/components/ui/toaster';
import { auth } from '@/auth';
import { WixMadeForText, arabicFont } from '@/lib/font';
import initTranslations from '@/lib/i18n';
import { LocaleT } from '@/types';
import { dir } from 'i18next';
import type { Metadata } from 'next';
import i18nConfig from '../../../i18nConfig';
import './globals.css';
import AuthProvider from '@/components/auth-provider';
import Header from '@/components/header';
import NavigationPrimary from '@/components/navigationPrimary';

export const metadata: Metadata = {
  title: 'Beyond Frontend',
  description: 'Generated by create next app',
};

const i18nNamespaces = ['nav'];

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: LocaleT;
  };
}>) {
  const { resources } = await initTranslations(locale, i18nNamespaces);
  const session = await auth();
  
  return (
    <html
      lang={locale}
      dir={dir(locale)}
      suppressHydrationWarning
      className='scroll-smooth'
    >
      <body
        className={
          locale === 'ar' ? arabicFont.className : WixMadeForText.className
        }
      >
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <AuthProvider>
            {/* <Header /> */}
            {/* <Navigation /> */}
            <NavigationPrimary isAuth={!!session} />
            {children}
            {/* <Footer /> */}
            <Footerprimary />
            <Toaster />
          </AuthProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
